### ISSUE TITLE
com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref 

### ISSUE THREAD

**Issue by tatavarthitarun** [HamidrezaAmz/MagicalExoPlayer#46]
I'm getting the following error, I have followed the instructions of usage given in the ReadMe file nothing much than that

Source error
      com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:779 in java.io.InputStreamReader@bc13d05) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:96)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:61)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:172)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: org.xmlpull.v1.XmlPullParserException: unterminated entity ref (position:TEXT @1:779 in java.io.InputStreamReader@bc13d05) 
        at com.android.org.kxml2.io.KXmlParser.readEntity(KXmlParser.java:1262)
        at com.android.org.kxml2.io.KXmlParser.readValue(KXmlParser.java:1465)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:408)
        at com.android.org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:89)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:61) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:172) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:919)

**Comment by HamidrezaAmz** [comment]
Hey @tatavarthitarun 
New version of MagicalExoPlayer is release, update your dependencies and check this problem.

**Comment by neeluagrawal04** [comment]
I am also facing same issue when download DRM enabled video via url and I am using  exoPlayerVersion = '2.13.3' as the version 
Can you help me to solve this issue?
