### ISSUE TITLE
com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ftypmp42��������

### ISSUE THREAD

**Issue by fvaldivian** [HamidrezaAmz/MagicalExoPlayer#53]
E/ExoPlayerImplInternal: Source error
      com.google.android.exoplayer2.ParserException: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ftypmp42��������...@6:87 in java.io.InputStreamReader@ed67357) 
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:96)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:61)
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:172)
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: org.xmlpull.v1.XmlPullParserException: Unexpected token (position:TEXT ������ftypmp42��������...@6:87 in java.io.InputStreamReader@ed67357) 
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:440)
        at org.kxml2.io.KXmlParser.next(KXmlParser.java:321)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:89)
        at com.google.android.exoplayer2.source.dash.manifest.DashManifestParser.parse(DashManifestParser.java:61) 
        at com.google.android.exoplayer2.upstream.ParsingLoadable.load(ParsingLoadable.java:172) 
        at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:391) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764)

**Comment by codaman** [comment]
i have same problem

**Comment by HamidrezaAmz** [comment]
New version on player is released today, let's work on new version. hope this issue is fixed.
